apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory-app
          image: docker.io/atuljkamble/inventory-management:latest
          ports:
            - containerPort: 5000
